
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module simpleMips(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [31:0] word;
	wire [1:0] select;
	wire [9:0] derreference;

	wire clockChoose, selectedClock, manualClock, reset, dividedClock;


//=======================================================
//  Structural coding
//=======================================================

	assign clockChoose = SW[0];
	assign manualClock = ~KEY[0];
	assign reset = ~KEY[3];
	assign select = SW[2:1];
	assign derreference = SW[17:8];

	clockDivider clockDivider0 (CLOCK_50, dividedClock);
	clockChooser clockChooser0 (clockChoose, dividedClock, manualClock, selectedClock);
	mips mips0 (selectedClock, reset, derreference, select, word);
	displaySevSegm displaySevSegm0 (CLOCK_50, word, HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, HEX6, HEX7);
	

endmodule
